// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import fs from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { expect, test } from "@playwright/test";

const runtimeObserved = new Map<string, Set<string>>();
const pendingRuntimeReceipts = new Map<string, object>();
const runtimeRegistryPath = path.resolve(process.cwd(), "testid-registry.json");
type RuntimeRegistry = { entries?: Array<{ id: string }>; patterns?: Array<{ pattern: string }> };
let runtimeRegistryPromise: Promise<RuntimeRegistry> | undefined;

function loadRuntimeRegistry() {
  runtimeRegistryPromise ??= fs.readFile(runtimeRegistryPath, "utf8").then((text) => JSON.parse(text));
  return runtimeRegistryPromise;
}

function registryKnows(testId: string, registry: RuntimeRegistry) {
  if ((registry.entries ?? []).some((entry) => entry.id === testId)) return true;
  return (registry.patterns ?? []).some((entry) => entry.pattern.endsWith("*") && testId.startsWith(entry.pattern.slice(0, -1)));
}


async function captureRuntimeObservation(page: import("@playwright/test").Page) {
  let lastError: unknown;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      return await page.evaluate(async () => {
        await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
        const RUNTIME_INTERACTIVE_SELECTOR =
          "button,input,select,textarea,a[href],summary,[contenteditable]:not([contenteditable='false']),[role='button'],[role='checkbox'],[role='combobox'],[role='link'],[role='menuitem'],[role='menuitemcheckbox'],[role='menuitemradio'],[role='option'],[role='radio'],[role='slider'],[role='spinbutton'],[role='switch'],[role='tab'],[role='textbox'],[role='treeitem'],[tabindex]:not([tabindex='-1'])";
        const RUNTIME_DEVTOOLS_ROOT_SELECTOR =
          "[data-agent-handles-devtools],[class*='TanStackRouterDevtools'],[id*='TanStackRouterDevtools'],[id*='tanstack-router-devtools'],[class*='tsqd-'],[class*='ReactQueryDevtools'],[id*='react-query-devtools'],vite-error-overlay,vite-plugin-checker-error-overlay";
        function isRuntimeObservationCandidate(element: Element) {
          if (element.closest("[data-agent-handles-overlay]")) return false;
          if (element.closest(RUNTIME_DEVTOOLS_ROOT_SELECTOR)) return false;
          if (element.closest('[aria-hidden="true"]')) return false;
          const role = element.getAttribute?.("role");
          const nativeControl = element.matches?.('button,input,select,textarea,a[href],summary,[contenteditable]:not([contenteditable="false"])');
          if ((role === "tablist" || role === "tabpanel") && !nativeControl) return false;
          const style = window.getComputedStyle(element);
          const rect = element.getBoundingClientRect();
          return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0;
        }
        const controls = Array.from(document.querySelectorAll(RUNTIME_INTERACTIVE_SELECTOR))
          .filter(isRuntimeObservationCandidate)
          .map((element) => ({
            testId: element.getAttribute("data-testid"),
            tag: element.tagName.toLowerCase(),
            role: element.getAttribute("role"),
            text: (element.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 120),
          }));
        const allIds = Array.from(document.querySelectorAll("[data-testid]"))
          .filter(isRuntimeObservationCandidate)
          .map((element) => element.getAttribute("data-testid"))
          .filter((value): value is string => Boolean(value));
        const duplicateTestIds = [...new Set(allIds.filter((value, index) => allIds.indexOf(value) !== index))].sort();
        return {
          url: location.href,
          controls,
          unidentified: controls.filter((control) => !control.testId),
          duplicateTestIds,
        };
      });
    } catch (error) {
      lastError = error;
      const navigationRace = /execution context was destroyed|most likely because of a navigation/iu.test(String(error));
      if (!navigationRace || attempt === 3) throw error;
      await page.waitForLoadState("domcontentloaded");
    }
  }
  throw lastError;
}

async function reconcileRuntime(page: import("@playwright/test").Page, journeyName: string, step: number, testInfo: import("@playwright/test").TestInfo) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const observed = runtimeObserved.get(testInfo.testId) ?? new Set<string>();
  for (const control of observation.controls) if (control.testId) observed.add(control.testId);
  runtimeObserved.set(testInfo.testId, observed);
  const receipt = {
    schema: "agent-handles/runtime-journey-observation/v1",
    measuredAt: new Date().toISOString(),
    journeyName,
    lastStep: step,
    pageUrl: observation.url,
    observedTestIds: [...observed].sort(),
    unidentified: observation.unidentified,
    unknownTestIds,
    duplicateTestIds: observation.duplicateTestIds,
    statement:
      [...observed].length +
      " controls observed during this journey; runtime evidence is path-bound, and unvisited states remain uncovered.",
  };
  pendingRuntimeReceipts.set(testInfo.testId, receipt);
  expect(observation.unidentified, "visible interactive controls without data-testid after step " + step).toEqual([]);
  expect(unknownTestIds, "visible controls with identity values absent from the registry after step " + step).toEqual([]);
  expect(observation.duplicateTestIds, "duplicate visible data-testid values after step " + step).toEqual([]);
}

async function recordFinalPageState(page: import("@playwright/test").Page, journeyName: string, testInfo: import("@playwright/test").TestInfo) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const directory = artifactDirectory(testInfo);
  const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
  const screenshotPath = path.join(directory, "final.png");
  await fs.mkdir(directory, { recursive: true });
  await page.screenshot({ path: screenshotPath, fullPage: true });
  const observedTestIds = [...new Set(observation.controls.map((control) => control.testId).filter(Boolean))].sort();
  const receipt = {
    schema: "agent-handles/page-state-review/v1",
    id: "journey-" + file,
    measuredAt: new Date().toISOString(),
    route: new URL(observation.url).pathname + new URL(observation.url).search,
    label: journeyName + " final state",
    title: await page.title(),
    evidenceKind: "compiled-journey-final",
    journeyName,
    visibleControls: observation.controls.length,
    identifiedControls: observation.controls.filter((control) => control.testId).length,
    issues: {
      unidentified: observation.unidentified.length,
      unknown: unknownTestIds.length,
      duplicate: observation.duplicateTestIds.length,
      reviewRequired: 0,
    },
    observedTestIds,
    screenshot: sha256(JSON.stringify(artifactIdentity(testInfo))) + "/final.png",
    statement:
      observation.controls.length +
      " controls observed in the final state of " +
      journeyName +
      "; this is page/state evidence, and unvisited states remain uncovered.",
  };
  pendingVisualReceipts.set(testInfo.testId, receipt);
}


const observationRunText = process.env.AGENT_HANDLES_OBSERVATION_RUN;
const observationRun = observationRunText ? JSON.parse(observationRunText) : null;
const manifestDigest = "6fd697cab1bf3742959f941da8732c1c6e6bff1e2899863659b23dc0e112e613";
const sha256 = (bytes: string | Buffer) => createHash("sha256").update(bytes).digest("hex");
const artifactIdentity = (testInfo: import("@playwright/test").TestInfo) => ({
  testId: testInfo.testId, project: testInfo.project.name, retry: testInfo.retry, repeatEachIndex: testInfo.repeatEachIndex,
});
function artifactDirectory(testInfo: import("@playwright/test").TestInfo) {
  const key = sha256(JSON.stringify(artifactIdentity(testInfo)));
  if (!observationRun) return testInfo.outputPath("agent-handles", key);
  if (observationRun.schema !== "agent-handles/observation-run/v1" || !path.isAbsolute(observationRun.directory)
    || typeof observationRun.runId !== "string" || observationRun.manifestDigest !== manifestDigest) {
    throw new Error("invalid or mismatched observation run context; regenerate journey spec");
  }
  return path.join(observationRun.directory, key);
}
const pendingVisualReceipts = new Map<string, object>();
test.afterEach(async ({ page: _page }, testInfo) => {
  const runtime = pendingRuntimeReceipts.get(testInfo.testId) as { journeyName: string } | undefined;
  if (!runtime) return;
  const directory = artifactDirectory(testInfo);
  await fs.mkdir(directory, { recursive: true });
  const identity = artifactIdentity(testInfo);
  const key = sha256(JSON.stringify(identity));
  const files: Record<string, { path: string; sha256: string }> = {};
  const save = async (kind: string, name: string, bytes: string | Buffer, contentType: string) => {
    await fs.writeFile(path.join(directory, name), bytes, { flag: "wx" });
    files[kind] = { path: key + "/" + name, sha256: sha256(bytes) };
    await testInfo.attach("agent-handles-" + kind, { path: path.join(directory, name), contentType });
  };
  await save("runtime", "runtime.json", JSON.stringify(runtime, null, 2) + "\n", "application/json");
  const visual = pendingVisualReceipts.get(testInfo.testId);
  if (visual) {
    const screenshot = await fs.readFile(path.join(directory, "final.png"));
    files.screenshot = { path: key + "/final.png", sha256: sha256(screenshot) };
    await testInfo.attach("agent-handles-screenshot", { path: path.join(directory, "final.png"), contentType: "image/png" });
    await save("visual", "visual.json", JSON.stringify(visual, null, 2) + "\n", "application/json");
  }
  const registryDigest = sha256(await fs.readFile(runtimeRegistryPath));
  if (observationRun && observationRun.registryDigest !== registryDigest) throw new Error("observation registry digest mismatch");
  const envelope = { run: observationRun ?? { schema: "agent-handles/observation-run/v1", runId: "playwright-artifact", manifestDigest, registryDigest },
    identity, journeyName: runtime.journeyName, status: testInfo.status, files };
  await fs.writeFile(path.join(directory, "receipt.json"), JSON.stringify(envelope, null, 2) + "\n", { flag: "wx" });
  await testInfo.attach("agent-handles-receipt", { path: path.join(directory, "receipt.json"), contentType: "application/json" });
  pendingRuntimeReceipts.delete(testInfo.testId);
  pendingVisualReceipts.delete(testInfo.testId);
  runtimeObserved.delete(testInfo.testId);
});

test("lookup-a-target: Set a target and see the matching adjacent-target control", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "lookup-a-target", 1, testInfo);
  await page.getByTestId("lookup.target.value").fill("24");
  await reconcileRuntime(page, "lookup-a-target", 2, testInfo);
  await expect(page.getByTestId("lookup.neighborhood.target-24")).toBeVisible();
  await reconcileRuntime(page, "lookup-a-target", 3, testInfo);
  await recordFinalPageState(page, "lookup-a-target", testInfo);
});

test("manage-competition-phases: Reach Competition through the chrome and open the phase manager", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "manage-competition-phases", 1, testInfo);
  await page.getByTestId("chrome.nav.item-compose").click();
  await reconcileRuntime(page, "manage-competition-phases", 2, testInfo);
  await page.getByTestId("compose.header.manage-phases").click();
  await reconcileRuntime(page, "manage-competition-phases", 3, testInfo);
  await expect(page.getByTestId("compose.phases.backdrop")).toBeVisible();
  await reconcileRuntime(page, "manage-competition-phases", 4, testInfo);
  await page.getByTestId("compose.phases.close").click();
  await reconcileRuntime(page, "manage-competition-phases", 5, testInfo);
  await recordFinalPageState(page, "manage-competition-phases", testInfo);
});

test("start-a-hard-quick-race: Reach Play, choose a bot difficulty, and start the race", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 1, testInfo);
  await page.getByTestId("chrome.nav.item-play").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 2, testInfo);
  await page.getByTestId("play.difficulty.select-hard").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 3, testInfo);
  await page.getByTestId("play.setup.begin").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 4, testInfo);
  await expect(page.getByTestId("play.board.player.cell-0")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "start-a-hard-quick-race", 5, testInfo);
  await recordFinalPageState(page, "start-a-hard-quick-race", testInfo);
});

test("competition-name-survives-reload: Rename the draft competition, reload, and check the restored name", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "competition-name-survives-reload", 1, testInfo);
  await page.getByTestId("chrome.nav.item-compose").click();
  await reconcileRuntime(page, "competition-name-survives-reload", 2, testInfo);
  await page.getByTestId("compose.header.rename").click();
  await reconcileRuntime(page, "competition-name-survives-reload", 3, testInfo);
  await page.getByTestId("compose.header.name-input").fill("Fictional saved draft");
  await reconcileRuntime(page, "competition-name-survives-reload", 4, testInfo);
  await page.getByTestId("compose.header.name-input").press("Enter");
  await reconcileRuntime(page, "competition-name-survives-reload", 5, testInfo);
  await page.goto("/");
  await reconcileRuntime(page, "competition-name-survives-reload", 6, testInfo);
  await page.getByTestId("chrome.nav.item-compose").click();
  await reconcileRuntime(page, "competition-name-survives-reload", 7, testInfo);
  await expect(page.getByTestId("compose.header.rename")).toContainText("Fictional saved draft");
  await reconcileRuntime(page, "competition-name-survives-reload", 8, testInfo);
  await recordFinalPageState(page, "competition-name-survives-reload", testInfo);
});

test("invalid-target-recovers: Clamp invalid zero target and recover to a valid query", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "invalid-target-recovers", 1, testInfo);
  await page.getByTestId("lookup.target.value").fill("0");
  await reconcileRuntime(page, "invalid-target-recovers", 2, testInfo);
  await page.getByTestId("lookup.target.value").press("Tab");
  await reconcileRuntime(page, "invalid-target-recovers", 3, testInfo);
  await page.getByTestId("lookup.target.value").fill("24");
  await reconcileRuntime(page, "invalid-target-recovers", 4, testInfo);
  await expect(page.getByTestId("lookup.neighborhood.target-24")).toBeVisible();
  await reconcileRuntime(page, "invalid-target-recovers", 5, testInfo);
  await recordFinalPageState(page, "invalid-target-recovers", testInfo);
});

test("forfeit-and-restart-quick-race: Forfeit one race and start a new race from setup", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 1, testInfo);
  await page.getByTestId("chrome.nav.item-play").click();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 2, testInfo);
  await page.getByTestId("play.setup.begin").click();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 3, testInfo);
  await expect(page.getByTestId("play.board.player.cell-0")).toBeVisible();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 4, testInfo);
  await page.getByTestId("play.race.forfeit").click();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 5, testInfo);
  await expect(page.getByTestId("play.setup.begin")).toBeVisible();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 6, testInfo);
  await page.getByTestId("play.setup.begin").click();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 7, testInfo);
  await expect(page.getByTestId("play.board.player.cell-0")).toBeVisible();
  await reconcileRuntime(page, "forfeit-and-restart-quick-race", 8, testInfo);
  await recordFinalPageState(page, "forfeit-and-restart-quick-race", testInfo);
});
