// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const runtimeObserved = new Map<string, Set<string>>();

async function reconcileRuntime(page: import("@playwright/test").Page, journeyName: string, step: number) {
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  const observation = await page.evaluate(() => {
    const selector = [
      "button", "input", "select", "textarea", "a[href]", "summary",
      "[contenteditable]:not([contenteditable='false'])",
      "[role='button']", "[role='link']", "[role='checkbox']", "[role='radio']",
      "[role='switch']", "[role='tab']", "[role='menuitem']", "[role='option']",
      "[role='combobox']", "[role='textbox']", "[role='slider']", "[role='spinbutton']",
      "[tabindex]:not([tabindex='-1'])",
    ].join(",");
    const visible = (element: Element) => {
      const style = window.getComputedStyle(element);
      const rect = element.getBoundingClientRect();
      return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0;
    };
    const controls = Array.from(document.querySelectorAll(selector)).filter(visible).map((element) => ({
      testId: element.getAttribute("data-testid"),
      tag: element.tagName.toLowerCase(),
      role: element.getAttribute("role"),
      text: (element.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 120),
    }));
    const allIds = Array.from(document.querySelectorAll("[data-testid]"))
      .filter(visible)
      .map((element) => element.getAttribute("data-testid"))
      .filter((value): value is string => Boolean(value));
    const duplicateTestIds = [...new Set(allIds.filter((value, index) => allIds.indexOf(value) !== index))].sort();
    return {
      url: location.href,
      controls,
      unidentified: controls.filter((control) => !control.testId),
      duplicateTestIds,
    };
  });
  const observed = runtimeObserved.get(journeyName) ?? new Set<string>();
  for (const control of observation.controls) if (control.testId) observed.add(control.testId);
  runtimeObserved.set(journeyName, observed);
  const receipt = {
    schema: "agent-handles/runtime-journey-observation/v1",
    measuredAt: new Date().toISOString(),
    journeyName,
    lastStep: step,
    pageUrl: observation.url,
    observedTestIds: [...observed].sort(),
    unidentified: observation.unidentified,
    duplicateTestIds: observation.duplicateTestIds,
    statement: [...observed].length + " controls observed during this journey; runtime evidence is path-bound, and unvisited states remain uncovered.",
  };
  const directory = path.join(process.cwd(), ".agent-handles", "runtime-observations");
  await fs.mkdir(directory, { recursive: true });
  const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
  await fs.writeFile(path.join(directory, file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
  expect(observation.unidentified, "visible interactive controls without data-testid after step " + step).toEqual([]);
  expect(observation.duplicateTestIds, "duplicate visible data-testid values after step " + step).toEqual([]);
}

test("lookup-a-target: Set a target and see the matching adjacent-target control", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "lookup-a-target", 1);
  await page.getByTestId("lookup.target.value").fill("24");
  await reconcileRuntime(page, "lookup-a-target", 2);
  await expect(page.getByTestId("lookup.neighborhood.target-24")).toBeVisible();
  await reconcileRuntime(page, "lookup-a-target", 3);
});

test("manage-competition-phases: Reach Competition through the chrome and open the phase manager", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "manage-competition-phases", 1);
  await page.getByTestId("chrome.nav.item-compose").click();
  await reconcileRuntime(page, "manage-competition-phases", 2);
  await page.getByTestId("compose.header.manage-phases").click();
  await reconcileRuntime(page, "manage-competition-phases", 3);
  await expect(page.getByTestId("compose.phases.backdrop")).toBeVisible();
  await reconcileRuntime(page, "manage-competition-phases", 4);
  await page.getByTestId("compose.phases.close").click();
  await reconcileRuntime(page, "manage-competition-phases", 5);
});

test("start-a-hard-quick-race: Reach Play, choose a bot difficulty, and start the race", async ({ page }) => {
  await page.goto("/");
  await page.getByTestId("welcome.actions.explore").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 1);
  await page.getByTestId("chrome.nav.item-play").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 2);
  await page.getByTestId("play.difficulty.select-hard").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 3);
  await page.getByTestId("play.setup.begin").click();
  await reconcileRuntime(page, "start-a-hard-quick-race", 4);
  await expect(page.getByTestId("play.board.player.cell-0")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "start-a-hard-quick-race", 5);
});
